import SwiftUI

/// App theme colors matching the web app design system
/// Colors are defined in Assets.xcassets/Colors and auto-generated by Xcode
enum AppColors {
    // MARK: - Brand Colors
    /// Primary accent color - Gold (#f6c343)
    static let accentGold = Color("AccentGold")

    // MARK: - Background Colors
    /// Primary background - Dark (#0a0a0a)
    static let backgroundPrimary = Color("BackgroundPrimary")
    /// Secondary background - Panels (#111111)
    static let backgroundSecondary = Color("BackgroundSecondary")

    // MARK: - Text Colors
    /// Primary text color (#e5e5e5)
    static let textPrimary = Color("TextPrimary")
    /// Secondary text color (#999999)
    static let textSecondary = Color("TextSecondary")

    // MARK: - Border Colors
    /// Standard border color (#222222)
    static let borderColor = Color("BorderColor")

    // MARK: - Status Colors
    /// Critical status - Red (#fca5a5)
    static let statusCritical = Color("StatusCritical")
    /// Warning status - Amber (#fcd34d)
    static let statusWarning = Color("StatusWarning")
    /// Normal/Success status - Green (#86efac)
    static let statusNormal = Color("StatusNormal")
}

/// Theme-aware view modifiers
extension View {
    /// Apply card styling with themed background
    func themedCard() -> some View {
        self
            .padding()
            .background(AppColors.backgroundSecondary)
            .cornerRadius(10)
            .overlay(
                RoundedRectangle(cornerRadius: 10)
                    .stroke(AppColors.borderColor, lineWidth: 0.5)
            )
    }

    /// Apply section background styling
    func themedSection() -> some View {
        self
            .padding()
            .background(AppColors.backgroundSecondary.opacity(0.5))
            .cornerRadius(10)
    }
}
